create table mat
(
	id bigint generated by default as identity,
	name text
);

comment on table mat is 'Таблица материалов';
comment on column mat.id is 'Первичный ключ';
comment on column mat.name is 'Наименование материала';
